name: Build and Release Dictionaries Monthly

on:
  schedule:
    - cron: '0 0 1 * *' # Runs at 00:00 (midnight) on the 1st day of every month
  workflow_dispatch: # Allows manually triggering the workflow

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get Current Date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Run Build Dicts Script
        run: |
          chmod +x ./binaries/yomitan
          bash build_dicts.sh

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: dst/*
          tag_name: ${{ steps.date.outputs.date }}
          name: ${{ steps.date.outputs.date }}
          token: ${{ secrets.GITHUB_TOKEN }}
